p1/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.index, name="home"),
]

p1/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("pages.urls")),
    path("blog/", include("blog.urls")),
    path('admin/', admin.site.urls),
]

p1/pages/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path('', views.index, name="home"),
    path('about/', views.about, name="about"),
    path('services/', views.services, name="services"),
]

p1/blog/models.py
from django.db import models

# Create your models here.

class Newarticle(models.Model):
    blog_title = models.CharField(max_length=200)
    blog_content = models.TextField()
    is_popular = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.blog_title
    

class Categories(models.Model):
    category_name = models.CharField(max_length=60)

    def __str__(self) -> str:
        return self.category_name


class Tags(models.Model):
    tag_name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.tag_name

p1/pages/models.py
from django.db import models

# Create your models here.

class Newpage(models.Model):
    page_title = models.CharField(max_length=200)
    page_content = models.TextField()
    
    def __str__(self) -> str:
        return self.page_title

p1/tools/models.py
from django.db import models

# Create your models here.

class topToolbar(models.Model):
    site_email = models.EmailField()
    site_address = models.TextField()
    site_contact = models.PositiveIntegerField()

    def __str__(self) -> str:
        return "Main Toolbar Content"

p1/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return HttpResponse("Hello World!")

p1/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from tools.models import topToolbar
# Create your views here.

def index(request):
    toolbar_data = topToolbar.objects.first()
    return render(request, "pages/index.html", {'toolbar_data': toolbar_data})

def about(request):
    toolbar_data = topToolbar.objects.first()
    return render(request, "pages/about.html", {'toolbar_data': toolbar_data})

def services(request):
    toolbar_data = topToolbar.objects.first()
    return render(request, "pages/services.html", {'toolbar_data': toolbar_data})

p1/tools/views.py
from django.shortcuts import render
from .models import topToolbar

# Create your views here.
def header_view(request):
    toolbar_data = topToolbar.objects.first()
    return render(request, 'toolbar.html', {'toolbar_data': toolbar_data})

p1/templates/base.html
{% include 'header.html' %}

{% block bodycontent %}
	
{% endblock bodycontent %}

{% include "footer.html" %}

p1/templates/footer.html
{% load static %}
<!-- footer Start -->
<footer class="footer section gray-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 mr-auto col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<div class="logo mb-4">
						<img src="images/logo.png" alt="" class="img-fluid">
					</div>
					<p>Tempora dolorem voluptatum nam vero assumenda voluptate, facilis ad eos obcaecati tenetur veritatis eveniet distinctio possimus.</p>

					<ul class="list-inline footer-socials mt-4">
						<li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i class="icofont-facebook"></i></a></li>
						<li class="list-inline-item"><a href="https://twitter.com/themefisher"><i class="icofont-twitter"></i></a></li>
						<li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i class="icofont-linkedin"></i></a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-2 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Department</h4>
					<div class="divider mb-4"></div>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="#">Surgery </a></li>
						<li><a href="#">Wome's Health</a></li>
						<li><a href="#">Radiology</a></li>
						<li><a href="#">Cardioc</a></li>
						<li><a href="#">Medicine</a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-2 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Support</h4>
					<div class="divider mb-4"></div>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="#">Terms & Conditions</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Company Support </a></li>
						<li><a href="#">FAQuestions</a></li>
						<li><a href="#">Company Licence</a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="widget widget-contact mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Get in Touch</h4>
					<div class="divider mb-4"></div>

					<div class="footer-contact-block mb-4">
						<div class="icon d-flex align-items-center">
							<i class="icofont-email mr-3"></i>
							<span class="h6 mb-0">Support Available for 24/7</span>
						</div>
						<h4 class="mt-2"><a href="tel:+23-345-67890">Support@email.com</a></h4>
					</div>

					<div class="footer-contact-block">
						<div class="icon d-flex align-items-center">
							<i class="icofont-support mr-3"></i>
							<span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
						</div>
						<h4 class="mt-2"><a href="tel:+23-345-67890">+23-456-6588</a></h4>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-btm py-4 mt-5">
			<div class="row align-items-center justify-content-between">
				<div class="col-lg-6">
					<div class="copyright">
						&copy; Copyright Reserved to <span class="text-color">Novena</span> by <a href="https://themefisher.com/" target="_blank">Themefisher</a>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="subscribe-form text-lg-right mt-5 mt-lg-0">
						<form action="#" class="subscribe">
							<input type="text" class="form-control" placeholder="Your Email address">
							<a href="#" class="btn btn-main-2 btn-round-full">Subscribe</a>
						</form>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4">
					<a class="backtop js-scroll-trigger" href="#top">
						<i class="icofont-long-arrow-up"></i>
					</a>
				</div>
			</div>
		</div>
	</div>
</footer>

   

    <!-- 
    Essential Scripts
    =====================================-->

    
    <!-- Main jQuery -->
    <script src="{% static 'plugins/jquery/jquery.js' %}"></script>
    <!-- Bootstrap 4.3.2 -->
    <script src="{% static 'plugins/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.easing.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <!-- Counterup -->
    <script src="{% static 'plugins/counterup/jquery.waypoints.min.js' %}"></script>
    
    <script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.counterup.min.js' %}"></script>
    <!-- Google Map -->
    <script src="{% static 'plugins/google-map/map.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>    
    
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>

  </body>
  </html>
   

p1/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Orbitor,business,company,agency,modern,bootstrap4,tech,software">
  <meta name="author" content="themefisher.com">

  <title>{{title}}</title>

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static '/images/favicon.ico' %}" />

  <!-- bootstrap.min css -->
  <link rel="stylesheet" href=" {% static 'plugins/bootstrap/css/bootstrap.min.css' %} ">
  <!-- Icon Font Css -->
  <link rel="stylesheet" href="{% static 'plugins/icofont/icofont.min.css' %}">
  <!-- Slick Slider  CSS -->
  <link rel="stylesheet" href="{% static 'plugins/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/slick-carousel/slick/slick-theme.css' %}">

  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body id="top">

<header>
    
	{% include "tools/toolbar.html" %}

	<nav class="navbar navbar-expand-lg navigation" id="navbar">
		<div class="container">
		 	 <a class="navbar-brand" href="index.html">
			  	<img src="{% static 'images/logo.png' %}" alt="" class="img-fluid">
			  </a>

		  	<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain" aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
			<span class="icofont-navigation-menu"></span>
		  </button>
	  
		  <div class="collapse navbar-collapse" id="navbarmain">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item active">
				<a class="nav-link" href="{% url 'pages:home' %}">Home</a>
			  </li>
			   <li class="nav-item"><a class="nav-link" href="{% url 'pages:about' %}">About</a></li>
			   <li class="nav-item"><a class="nav-link" href="{% url 'pages:services' %}">Services</a></li>
               <li class="nav-item"><a class="nav-link" href="{% url 'pages:services' %}">Blog</a></li>
			   <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="blog-sidebar.html" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Blog <i class="icofont-thin-down"></i></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown05">
						<li><a class="dropdown-item" href="blog-sidebar.html">Blog with Sidebar</a></li>

						<li><a class="dropdown-item" href="blog-single.html">Blog Single</a></li>
					</ul>
			  	</li>
			   <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
			</ul>
		  </div>
		</div>
	</nav>
</header>

p1/templates/pages/about.html
{% include "header.html" %}
{% load static %}
<section class="page-title bg-1">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="block text-center">
            <span class="text-white">About Us</span>
            <h1 class="text-capitalize mb-5 text-lg">About Us</h1>
  
            <!-- <ul class="list-inline breadcumb-nav">
              <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
              <li class="list-inline-item"><span class="text-white">/</span></li>
              <li class="list-inline-item"><a href="#" class="text-white-50">About Us</a></li>
            </ul> -->
          </div>
        </div>
      </div>
    </div>
  </section>
  
  <section class="section about-page">
      <div class="container">
          <div class="row">
              <div class="col-lg-4">
                  <h2 class="title-color">Personal care for your healthy living</h2>
              </div>
              <div class="col-lg-8">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, quod laborum alias. Vitae dolorum, officia sit! Saepe ullam facere at, consequatur incidunt, quae esse, quis ut reprehenderit dignissimos, libero delectus.</p>
                  <img src="{% static 'images/about/sign.png' %}" alt="" class="img-fluid">
              </div>
          </div>
      </div>
  </section>
  
  <section class="fetaure-page ">
      <div class="container">
          <div class="row">
              <div class="col-lg-3 col-md-6">
                  <div class="about-block-item mb-5 mb-lg-0">
                      <img src="{% static 'images/about/about-1.jpg' %}" alt="" class="img-fluid w-100">
                      <h4 class="mt-3">Healthcare for Kids</h4>
                      <p>Voluptate aperiam esse possimus maxime repellendus, nihil quod accusantium .</p>
                  </div>
              </div>
              <div class="col-lg-3 col-md-6">
                  <div class="about-block-item mb-5 mb-lg-0">
                      <img src="{% static 'images/about/about-2.jpg' %}" alt="" class="img-fluid w-100">
                      <h4 class="mt-3">Medical Counseling</h4>
                      <p>Voluptate aperiam esse possimus maxime repellendus, nihil quod accusantium .</p>
                  </div>
              </div>
              <div class="col-lg-3 col-md-6">
                  <div class="about-block-item mb-5 mb-lg-0">
                      <img src="{% static 'images/about/about-3.jpg' %}" alt="" class="img-fluid w-100">
                      <h4 class="mt-3">Modern Equipments</h4>
                      <p>Voluptate aperiam esse possimus maxime repellendus, nihil quod accusantium .</p>
                  </div>
              </div>
              <div class="col-lg-3 col-md-6">
                  <div class="about-block-item">
                      <img src="{% static 'images/about/about-4.jpg' %}" alt="" class="img-fluid w-100">
                      <h4 class="mt-3">Qualified Doctors</h4>
                      <p>Voluptate aperiam esse possimus maxime repellendus, nihil quod accusantium .</p>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section class="section awards">
      <div class="container">
          <div class="row align-items-center">
              <div class="col-lg-4">
                  <h2 class="title-color">Our Doctors achievements </h2>
                  <div class="divider mt-4 mb-5 mb-lg-0"></div>
              </div>
              <div class="col-lg-8">
                  <div class="row">
                      <div class="col-lg-4 col-md-6 col-sm-6">
                          <div class="award-img">
                              <img src="{% static 'images/about/3.png' %}" alt="" class="img-fluid">
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                          <div class="award-img">
                              <img src="{% static 'images/about/4.png' %}" alt="" class="img-fluid">
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                          <div class="award-img">
                              <img src="{% static 'images/about/1.png' %}" alt="" class="img-fluid">
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                          <div class="award-img">
                              <img src="{% static 'images/about/2.png' %}" alt="" class="img-fluid">
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                          <div class="award-img">
                              <img src="{% static 'images/about/5.png' %}" alt="" class="img-fluid">
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6">
                          <div class="award-img">
                              <img src="{% static 'images/about/6.png' %}" alt="" class="img-fluid">
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  
  <section class="section team">
      <div class="container">
          <div class="row justify-content-center">
              <div class="col-lg-6">
                  <div class="section-title text-center">
                      <h2 class="mb-4">Meet Our Specialist</h2>
                      <div class="divider mx-auto my-4"></div>
                      <p>Today’s users expect effortless experiences. Don’t let essential people and processes stay stuck in the past. Speed it up, skip the hassles</p>
                  </div>
              </div>
          </div>
  
          <div class="row">
              <div class="col-lg-3 col-md-6 col-sm-6">
                  <div class="team-block mb-5 mb-lg-0">
                      <img src="{% static 'images/team/1.jpg' %}" alt="" class="img-fluid w-100">
  
                      <div class="content">
                          <h4 class="mt-4 mb-0"><a href="doctor-single.html">John Marshal</a></h4>
                          <p>Internist, Emergency Physician</p>
                      </div>
                  </div>
              </div>
  
              <div class="col-lg-3 col-md-6 col-sm-6">
                  <div class="team-block mb-5 mb-lg-0">
                      <img src="{% static 'images/team/2.jpg' %}" alt="" class="img-fluid w-100">
  
                      <div class="content">
                          <h4 class="mt-4 mb-0"><a href="doctor-single.html">Marshal Root</a></h4>
                          <p>Surgeon, Сardiologist</p>
                      </div>
                  </div>
              </div>
  
              <div class="col-lg-3 col-md-6 col-sm-6">
                  <div class="team-block mb-5 mb-lg-0">
                      <img src="{% static 'images/team/3.jpg' %}" alt="" class="img-fluid w-100">
  
                      <div class="content">
                          <h4 class="mt-4 mb-0"><a href="doctor-single.html">Siamon john</a></h4>
                          <p>Internist, General Practitioner</p>
                      </div>
                  </div>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-6">
                  <div class="team-block">
                      <img src="{% static 'images/team/4.jpg' %}" alt="" class="img-fluid w-100">
  
                      <div class="content">
                          <h4 class="mt-4 mb-0"><a href="doctor-single.html">Rishat Ahmed</a></h4>
                          <p>Orthopedic Surgeon</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  
  <section class="section testimonial">
      <div class="container">
          <div class="row">
              <div class="col-lg-6 offset-lg-6">
                  <div class="section-title">
                      <h2 class="mb-4">What they say about us</h2>
                      <div class="divider  my-4"></div>
                  </div>
              </div>
          </div>
          <div class="row align-items-center">
              <div class="col-lg-6 testimonial-wrap offset-lg-6">
                  <div class="testimonial-block">
                      <div class="client-info ">
                          <h4>Amazing service!</h4>
                          <span>John Partho</span>
                      </div>
                      <p>
                          They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet nostrum nemo commodi numquam quod.
                      </p>
                      <i class="icofont-quote-right"></i>
                      
                  </div>
  
                  <div class="testimonial-block">
                      <div class="client-info">
                          <h4>Expert doctors!</h4>
                          <span>Mullar Sarth</span>
                      </div>
                      <p>
                          They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet nostrum nemo commodi numquam quod.
                      </p>
                      <i class="icofont-quote-right"></i>
                  </div>
  
                  <div class="testimonial-block">
                      <div class="client-info">
                          <h4>Good Support!</h4>
                          <span>Kolis Mullar</span>
                      </div>
                      <p>
                          They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet nostrum nemo commodi numquam quod.
                      </p>
                      <i class="icofont-quote-right"></i>
                  </div>
  
                  <div class="testimonial-block">
                      <div class="client-info">
                          <h4>Nice Environment!</h4>
                          <span>Partho Sarothi</span>
                      </div>
                      <p>
                          They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet nostrum nemo commodi numquam quod.
                      </p>
                      <i class="icofont-quote-right"></i>
                  </div>
  
                  <div class="testimonial-block">
                      <div class="client-info">
                          <h4>Modern Service!</h4>
                          <span>Kolis Mullar</span>
                      </div>
                      <p>
                          They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet nostrum nemo commodi numquam quod.
                      </p>
                      <i class="icofont-quote-right"></i>
                  </div>
              </div>
          </div>
      </div>
  </section>
  {% include "footer.html" %}

p1/templates/pages/services.html
{% include "header.html" %}
<section class="page-title bg-1">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="block text-center">
            <span class="text-white">Our services</span>
            <h1 class="text-capitalize mb-5 text-lg">What We Do</h1>
  
            <!-- <ul class="list-inline breadcumb-nav">
              <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
              <li class="list-inline-item"><span class="text-white">/</span></li>
              <li class="list-inline-item"><a href="#" class="text-white-50">Our services</a></li>
            </ul> -->
          </div>
        </div>
      </div>
    </div>
  </section>
  
  
  <section class="section service-2">
      <div class="container">
          <div class="row">
              <div class="col-lg-4 col-md-6 col-sm-6">
                  <div class="service-block mb-5">
                      <img src="images/service/service-1.jpg" alt="" class="img-fluid">
                      <div class="content">
                          <h4 class="mt-4 mb-2 title-color">Child care</h4>
                          <p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
                      </div>
                  </div>
              </div>
  
              <div class="col-lg-4 col-md-6 col-sm-6">
                  <div class="service-block mb-5">
                      <img src="images/service/service-2.jpg" alt="" class="img-fluid">
                      <div class="content">
                          <h4 class="mt-4 mb-2  title-color">Personal Care</h4>
                          <p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
                      </div>
                  </div>
              </div>
              
              <div class="col-lg-4 col-md-6 col-sm-6">
                  <div class="service-block mb-5">
                      <img src="images/service/service-3.jpg" alt="" class="img-fluid">
                      <div class="content">
                          <h4 class="mt-4 mb-2 title-color">CT scan</h4>
                          <p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
                      </div>
                  </div>
              </div>
  
  
              <div class="col-lg-4 col-md-6 col-sm-6">
                  <div class="service-block mb-5 mb-lg-0">
                      <img src="images/service/service-4.jpg" alt="" class="img-fluid">
                      <div class="content">
                          <h4 class="mt-4 mb-2 title-color">Joint replacement</h4>
                          <p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
                      </div>
                  </div>
              </div>
  
              <div class="col-lg-4 col-md-6 col-sm-6">
                  <div class="service-block mb-5 mb-lg-0">
                      <img src="images/service/service-6.jpg" alt="" class="img-fluid">
                      <div class="content">
                          <h4 class="mt-4 mb-2 title-color">Examination & Diagnosis</h4>
                          <p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
                      </div>
                  </div>
              </div>
              
              <div class="col-lg-4 col-md-6 col-sm-6">
                  <div class="service-block mb-5 mb-lg-0">
                      <img src="images/service/service-8.jpg" alt="" class="img-fluid">
                      <div class="content">
                          <h4 class="mt-4 mb-2 title-color">Alzheimer's disease</h4>
                          <p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section class="section cta-page">
      <div class="container">
          <div class="row">
              <div class="col-lg-7">
                  <div class="cta-content">
                      <div class="divider mb-4"></div>
                      <h2 class="mb-5 text-lg">We are pleased to offer you the <span class="title-color">chance to have the healthy</span></h2>
                      <a href="appoinment.html" class="btn btn-main-2 btn-round-full">Get appoinment<i class="icofont-simple-right  ml-2"></i></a>
                  </div>
              </div>
          </div>
      </div>
  </section>

  {% include "footer.html" %}

p1/templates/tools/toolbar.html
    
<div class="header-top-bar">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <ul class="top-bar-info list-inline-item pl-0 mb-0">
                    <li class="list-inline-item"><a href="mailto:support@gmail.com"><i class="icofont-support-faq mr-2"></i>{{  toolbar_data.site_email }}</a></li>
                    <li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>{{ toolbar_data.site_address }}</li>
                </ul>
            </div>
            <div class="col-lg-6">
                <div class="text-lg-right top-right-bar mt-2 mt-lg-0">
                    <a href="tel:+23-345-67890" >
                        <span>Call Now : </span>
                        <span class="h4">{{ toolbar_data.site_contact }}</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>